### ISSUE TITLE
`exodus_analyze.py` crash analazing a `aab` format application

### ISSUE THREAD

**Issue by jfoucry** [Exodus-Privacy/exodus-standalone#28]
Here is the log:
```
python3.8 exodus_analyze.py ~/StudioProjects/Pilldroid/app/product/release/app-product-release.aab 
Missing AndroidManifest.xml. Is this an APK file?
=== Information
- APK path: /home/jacques/StudioProjects/Pilldroid/app/product/release/app-product-release.aab
- APK sum: f978a7ce751609a750341d099fd498f0953865df949d2263548e5848b152e744
Traceback (most recent call last):
  File "exodus_analyze.py", line 78, in <module>
    main()
  File "exodus_analyze.py", line 71, in main
    analysis.print_apk_infos()
  File "/home/jacques/exodus-standalone/test_app_venv/lib/python3.8/site-packages/exodus_core/analysis/static_analysis.py", line 471, in print_apk_infos
    print('- App version: {}'.format(self.get_version()))
  File "/home/jacques/exodus-standalone/test_app_venv/lib/python3.8/site-packages/exodus_core/analysis/static_analysis.py", line 239, in get_version
    return self.apk.get_androidversion_name()
  File "/home/jacques/exodus-standalone/test_app_venv/lib/python3.8/site-packages/androguard/core/bytecodes/apk.py", line 620, in get_androidversion_name
    return self.androidversion["Name"]
KeyError: 'Name'
```

With `unzip -l ~/StudioProjects/Pilldroid/app/product/release/app-product-release.aab` I actually can't find the `AndroidManifest.xml` file.

**Comment by pnu-s** [comment]
The issue seems to come from our call to the Androguard library, which is not maintained anymore and I'm unsure whether it supports aab application format (it probably does not).

**Comment by jfoucry** [comment]
This is annoying because since august 2021 `aab` is the new format for Android applications. Did we are a `androguard` replacement?
